[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false

[package]
name = "pdu-mib-gen-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
